export const intentType = {
  ADD_PAGE: "add_page",
  ADD_SECTION: "add_section",
  MODIFY_SECTION: "modify_section",
  MODIFY_TEXT_CONTENT: "modify_text_content",
  MODIFY_STYLING: "modify_styling",
  ADD_NEW_SERVICE: "add_new_service",
  MODIFY_SERVICE: "modify_service",
  CONNECT_AI: "connect_ai",
  DB_CONNECTION: "db_connection",
  ADD_NEW_TABLE: "add_new_table",
  MODIFY_SCHEMA: "modify_schema",
  MODIFY_TABLE: "modify_table",
  ADD_NEW_COLUMN: "add_new_column",
  MODIFY_COLUMN: "modify_column",
};
